///////////////////////////////////////////////////////////////////////////
// Description: DataObject class for the 'GLENTRY'
// Generated by vnyi GenTool.
// Copyright (c) YI. All rights reserved.
///////////////////////////////////////////////////////////////////////////

using System;
using System.Data;
using vnyi.DataProvider;
using System.Data.SqlClient;
using System.Collections.Generic;

namespace vnyi.Library.COMON.IV
{
    public class GLENTRYDAO
    {
        
      
    }
}
