///////////////////////////////////////////////////////////////////////////
// Description: Entity class for the 'GLENTRY'
// Generated by VNYI GenTool.
// Copyright (c) YI Corp. All rights reserved.// Design by ngocchinh.//email:ngocchinh4984@gmail.com
///////////////////////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;

using System.Data;

namespace vnyi.Library.COMON.IV{
public class GLENTRY : vnyi.DLL.DataObject
	{

public static string COLUMN_COT_DOCUMENTID="COT_DOCUMENTID";
public static string COLUMN_CP_AUTOID="CP_AUTOID";
public static string COLUMN_GL_DOCUMENTID="GL_DOCUMENTID";
public static string COLUMN_GLE_AUTOID="GLE_AUTOID";
public static string COLUMN_IVDC_DOCCUMENTID="IVDC_DOCCUMENTID";
public static string COLUMN_GLE_EXCHANGERATE="GLE_EXCHANGERATE";
public static string COLUMN_GLE_AMOUNT="GLE_AMOUNT";
public static string COLUMN_OBJ_AUTOID="OBJ_AUTOID";
public static string COLUMN_GLE_DESCRIPTION="GLE_DESCRIPTION";
public static string COLUMN_PETT_AUTOID="PETT_AUTOID";
public static string COLUMN_PRJ_AUTOID="PRJ_AUTOID";
public static string COLUMN_CUR_AUTOID="CUR_AUTOID";
public static string COLUMN_GLE_DEBTORAMOUNT="GLE_DEBTORAMOUNT";
public static string COLUMN_ACC_CORRESPONDING="ACC_CORRESPONDING";
public static string COLUMN_GLE_CREDITAMOUNT="GLE_CREDITAMOUNT";
public static string COLUMN_ACC_ACCOUNT="ACC_ACCOUNT";

public static string TABLE_NAME ="GLENTRY";

public Nullable<Int64> GLE_AUTOID
	{	get
		{
			return ConvertToInt64(_dataRow[COLUMN_GLE_AUTOID]);
		}
	set
		{
			_dataRow[COLUMN_GLE_AUTOID] =value;
		}
		}
public Nullable<Int64> IVDC_DOCCUMENTID
	{	get
		{
			return ConvertToInt64(_dataRow[COLUMN_IVDC_DOCCUMENTID]);
		}
	set
		{
			_dataRow[COLUMN_IVDC_DOCCUMENTID] =value;
		}
		}
public Nullable<Int64> GL_DOCUMENTID
	{	get
		{
			return ConvertToInt64(_dataRow[COLUMN_GL_DOCUMENTID]);
		}
	set
		{
			_dataRow[COLUMN_GL_DOCUMENTID] =value;
		}
		}
public Nullable<int> OBJ_AUTOID
	{	get
		{
			return ConvertToInt32(_dataRow[COLUMN_OBJ_AUTOID]);
		}
	set
		{
			_dataRow[COLUMN_OBJ_AUTOID] = value;
		}
		}
public Nullable<Int64> CP_AUTOID
	{	get
		{
			return ConvertToInt64(_dataRow[COLUMN_CP_AUTOID]);
		}
	set
		{
			_dataRow[COLUMN_CP_AUTOID] =value;
		}
		}
public Nullable<Int16> PRJ_AUTOID
	{	get
		{
			return ConvertToInt16(_dataRow[COLUMN_PRJ_AUTOID]);
		}
	set
		{
			_dataRow[COLUMN_PRJ_AUTOID] = value;
		}
		}
public Nullable<Int64> COT_DOCUMENTID
	{	get
		{
			return ConvertToInt64(_dataRow[COLUMN_COT_DOCUMENTID]);
		}
	set
		{
			_dataRow[COLUMN_COT_DOCUMENTID] =value;
		}
		}
public Nullable<Decimal> GLE_AMOUNT
	{	get
		{
			 return ConvertDecimalnull(_dataRow[COLUMN_GLE_AMOUNT]);
		}
	set
		{
			_dataRow[COLUMN_GLE_AMOUNT] =value;
		}
		}
public Nullable<Int16> CUR_AUTOID
	{	get
		{
			return ConvertToInt16(_dataRow[COLUMN_CUR_AUTOID]);
		}
	set
		{
			_dataRow[COLUMN_CUR_AUTOID] = value;
		}
		}
public Nullable<Decimal> GLE_EXCHANGERATE
	{	get
		{
			 return ConvertDecimalnull(_dataRow[COLUMN_GLE_EXCHANGERATE]);
		}
	set
		{
			_dataRow[COLUMN_GLE_EXCHANGERATE] =value;
		}
		}
public String GLE_CREDITAMOUNT
	{	get
		{
			return Convert.ToString(GetSafeObjectValue(_dataRow[COLUMN_GLE_CREDITAMOUNT], null));
		}
	set
		{
			_dataRow[COLUMN_GLE_CREDITAMOUNT] =value;
		}
		}
public String GLE_DEBTORAMOUNT
	{	get
		{
			return Convert.ToString(GetSafeObjectValue(_dataRow[COLUMN_GLE_DEBTORAMOUNT], null));
		}
	set
		{
			_dataRow[COLUMN_GLE_DEBTORAMOUNT] =value;
		}
		}
public String ACC_ACCOUNT
	{	get
		{
			return Convert.ToString(GetSafeObjectValue(_dataRow[COLUMN_ACC_ACCOUNT], null));
		}
	set
		{
			_dataRow[COLUMN_ACC_ACCOUNT] =value;
		}
		}
public String ACC_CORRESPONDING
	{	get
		{
			return Convert.ToString(GetSafeObjectValue(_dataRow[COLUMN_ACC_CORRESPONDING], null));
		}
	set
		{
			_dataRow[COLUMN_ACC_CORRESPONDING] =value;
		}
		}
public String GLE_DESCRIPTION
	{	get
		{
			return Convert.ToString(GetSafeObjectValue(_dataRow[COLUMN_GLE_DESCRIPTION], null));
		}
	set
		{
			_dataRow[COLUMN_GLE_DESCRIPTION] =value;
		}
		}
public Nullable<Int16> PETT_AUTOID
	{	get
		{
			return ConvertToInt16(_dataRow[COLUMN_PETT_AUTOID]);
		}
	set
		{
			_dataRow[COLUMN_PETT_AUTOID] = value;
		}
		}
public GLENTRY(IDataReader RederObject) : base(RederObject, TABLE_NAME) { }
public GLENTRY(DataRow row) : base(row, TABLE_NAME) { }
public GLENTRY()
: base(TABLE_NAME, COLUMN_GLE_AUTOID, 
COLUMN_IVDC_DOCCUMENTID, 
COLUMN_GL_DOCUMENTID, 
COLUMN_OBJ_AUTOID, 
COLUMN_CP_AUTOID, 
COLUMN_PRJ_AUTOID, 
COLUMN_COT_DOCUMENTID, 
COLUMN_GLE_AMOUNT, 
COLUMN_CUR_AUTOID, 
COLUMN_GLE_EXCHANGERATE, 
COLUMN_GLE_CREDITAMOUNT, 
COLUMN_GLE_DEBTORAMOUNT, 
COLUMN_ACC_ACCOUNT, 
COLUMN_ACC_CORRESPONDING, 
COLUMN_GLE_DESCRIPTION, 
COLUMN_PETT_AUTOID) { }
	}
}

