///////////////////////////////////////////////////////////////////////////
// Description: Entity class for the 'INVOICEDETAIL'
// Generated by VNYI GenTool.
// Copyright (c) YI Corp. All rights reserved.// Design by ngocchinh.//email:ngocchinh4984@gmail.com
///////////////////////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;

using System.Data;

namespace vnyi.Library.COMON.IV
{
    public class INVOICEDETAIL : vnyi.DLL.DataObject
    {

        public static string COLUMN_IV_DOCUMENTID = "IV_DOCUMENTID";
        public static string COLUMN_IVD_AUTOID = "IVD_AUTOID";
        public static string COLUMN_IVD_VATTAXPER = "IVD_VATTAXPER";
        public static string COLUMN_IVD_VATTAXAMOUNT = "IVD_VATTAXAMOUNT";
        public static string COLUMN_IVD_VATTAXBASEAMOUNT = "IVD_VATTAXBASEAMOUNT";
        public static string COLUMN_IVD_REDUCEBASEAMOUNT = "IVD_REDUCEBASEAMOUNT";
        public static string COLUMN_IVD_ITEMBASEAMOUNT = "IVD_ITEMBASEAMOUNT";
        public static string COLUMN_IVD_REDUCEPER = "IVD_REDUCEPER";
        public static string COLUMN_IVD_REDUCEAMOUNT = "IVD_REDUCEAMOUNT";
        public static string COLUMN_IVD_EXCISETAXPER = "IVD_EXCISETAXPER";
        public static string COLUMN_IVD_IMEXPORTTAXBASEAMOUNT = "IVD_IMEXPORTTAXBASEAMOUNT";
        public static string COLUMN_IVD_TOTALAMOUNT = "IVD_TOTALAMOUNT";
        public static string COLUMN_IVD_TOTALBASEAMOUNT = "IVD_TOTALBASEAMOUNT";
        public static string COLUMN_IVD_IMEXPORTTAXAMOUNT = "IVD_IMEXPORTTAXAMOUNT";
        public static string COLUMN_IVD_EXCISETAXAMOUNT = "IVD_EXCISETAXAMOUNT";
        public static string COLUMN_IVD_EXCISETAXBASEAMOUNT = "IVD_EXCISETAXBASEAMOUNT";
        public static string COLUMN_IVD_IMEXPORTTAXPER = "IVD_IMEXPORTTAXPER";
        public static string COLUMN_IVD_ITEMAMOUNT = "IVD_ITEMAMOUNT";
        public static string COLUMN_IVD_QUANTITYREAL = "IVD_QUANTITYREAL";
        public static string COLUMN_IVD_REQQUANTITY = "IVD_REQQUANTITY";
        public static string COLUMN_IVD_UNITBASEPRICE = "IVD_UNITBASEPRICE";
        public static string COLUMN_IVD_UNITPRICE = "IVD_UNITPRICE";
        public static string COLUMN_WH_AUTOID = "WH_AUTOID";
        public static string COLUMN_COT_DOCUMENTID = "COT_DOCUMENTID";
        public static string COLUMN_CP_AUTOID = "CP_AUTOID";
        public static string COLUMN_PIT_AUTOID = "PIT_AUTOID";
        public static string COLUMN_PIT_ITEMNAME = "PIT_ITEMNAME";
        public static string COLUMN_PIT_ITEMNO = "PIT_ITEMNO";
        public static string COLUMN_IVD_DESCRIPTION = "IVD_DESCRIPTION";
        public static string COLUMN_ITG_AUTOID = "ITG_AUTOID";
        public static string COLUMN_TUR_AUTOID = "TUR_AUTOID";
        public static string COLUMN_UOM_AUTOID = "UOM_AUTOID";
        public static string COLUMN_ITT_AUTOID = "ITT_AUTOID";
        public static string COLUMN_PK_AUTOID = "PK_AUTOID";

        public static string TABLE_NAME = "INVOICEDETAIL";

        public Nullable<Int64> IVD_AUTOID
        {
            get
            {
                return ConvertToInt64(_dataRow[COLUMN_IVD_AUTOID]);
            }
            set
            {
                _dataRow[COLUMN_IVD_AUTOID] = value;
            }
        }
        public Nullable<Int64> IV_DOCUMENTID
        {
            get
            {
                return ConvertToInt64(_dataRow[COLUMN_IV_DOCUMENTID]);
            }
            set
            {
                _dataRow[COLUMN_IV_DOCUMENTID] = value;
            }
        }
        public Nullable<Int16> ITG_AUTOID
        {
            get
            {
                return ConvertToInt16(_dataRow[COLUMN_ITG_AUTOID]);
            }
            set
            {
                _dataRow[COLUMN_ITG_AUTOID] = value;
            }
        }
        public Nullable<int> CP_AUTOID
        {
            get
            {
                return ConvertToInt32(_dataRow[COLUMN_CP_AUTOID]);
            }
            set
            {
                _dataRow[COLUMN_CP_AUTOID] = value;
            }
        }
        public Nullable<Int16> PK_AUTOID
        {
            get
            {
                return ConvertToInt16(_dataRow[COLUMN_PK_AUTOID]);
            }
            set
            {
                _dataRow[COLUMN_PK_AUTOID] = value;
            }
        }
        public Nullable<int> PIT_AUTOID
        {
            get
            {
                return ConvertToInt32(_dataRow[COLUMN_PIT_AUTOID]);
            }
            set
            {
            
                _dataRow[COLUMN_PIT_AUTOID] =GetSafeObjectValue(value,null);
            }
        }
        public String PIT_ITEMNAME
        {
            get
            {
                return Convert.ToString(GetSafeObjectValue(_dataRow[COLUMN_PIT_ITEMNAME], null));
            }
            set
            {
                _dataRow[COLUMN_PIT_ITEMNAME] = GetSafeObjectValue(value, null);
            }
        }
        public String PIT_ITEMNO
        {
            get
            {
                return Convert.ToString(GetSafeObjectValue(_dataRow[COLUMN_PIT_ITEMNO], null));
            }
            set
            {
                _dataRow[COLUMN_PIT_ITEMNO] = value;
            }
        }
        public Nullable<int> COT_DOCUMENTID
        {
            get
            {
                return ConvertToInt32(_dataRow[COLUMN_COT_DOCUMENTID]);
            }
            set
            {
                _dataRow[COLUMN_COT_DOCUMENTID] = value;
            }
        }
        public Nullable<Int16> TUR_AUTOID
        {
            get
            {
                return ConvertToInt16(_dataRow[COLUMN_TUR_AUTOID]);
            }
            set
            {
                _dataRow[COLUMN_TUR_AUTOID] = value;
            }
        }
        public Nullable<int> WH_AUTOID
        {
            get
            {
                return ConvertToInt32(_dataRow[COLUMN_WH_AUTOID]);
            }
            set
            {
                _dataRow[COLUMN_WH_AUTOID] = value;
            }
        }
        public Nullable<Int16> ITT_AUTOID
        {
            get
            {
                return ConvertToInt16(_dataRow[COLUMN_ITT_AUTOID]);
            }
            set
            {
                _dataRow[COLUMN_ITT_AUTOID] = value;
            }
        }
        public Nullable<Int16> UOM_AUTOID
        {
            get
            {
                return ConvertToInt16(_dataRow[COLUMN_UOM_AUTOID]);
            }
            set
            {
                _dataRow[COLUMN_UOM_AUTOID] = value;
            }
        }
        public Nullable<Decimal> IVD_REQQUANTITY
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_IVD_REQQUANTITY]);
            }
            set
            {
                if (value != null)
                    _dataRow[COLUMN_IVD_REQQUANTITY] = value;

                else
                    _dataRow[COLUMN_IVD_REQQUANTITY] = DBNull.Value;
            }
        }
        public Nullable<Decimal> IVD_QUANTITYREAL
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_IVD_QUANTITYREAL]);
            }
            set
            {
                if (value != null)
                    _dataRow[COLUMN_IVD_QUANTITYREAL] = value;

                else
                    _dataRow[COLUMN_IVD_QUANTITYREAL] = DBNull.Value;

            }
        }
        public Nullable<Decimal> IVD_UNITPRICE
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_IVD_UNITPRICE]);
            }
            set
            {
                if (value != null)
                    _dataRow[COLUMN_IVD_UNITPRICE] = value;

                else
                    _dataRow[COLUMN_IVD_UNITPRICE] = DBNull.Value;

            }
        }
        public Nullable<Decimal> IVD_UNITBASEPRICE
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_IVD_UNITBASEPRICE]);
            }
            set
            {
                if (value != null)
                    _dataRow[COLUMN_IVD_UNITBASEPRICE] = value;

                else
                    _dataRow[COLUMN_IVD_UNITBASEPRICE] = DBNull.Value;


            }
        }
        public Nullable<Decimal> IVD_ITEMAMOUNT
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_IVD_ITEMAMOUNT]);
            }
            set
            {
                if (value != null)
                    _dataRow[COLUMN_IVD_ITEMAMOUNT] = value;

                else
                    _dataRow[COLUMN_IVD_ITEMAMOUNT] = DBNull.Value;

            }
        }
        public Nullable<Decimal> IVD_ITEMBASEAMOUNT
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_IVD_ITEMBASEAMOUNT]);
            }
            set
            {
                if (value != null)
                    _dataRow[COLUMN_IVD_ITEMBASEAMOUNT] = value;

                else
                    _dataRow[COLUMN_IVD_ITEMBASEAMOUNT] = DBNull.Value;

            }
        }
        public Nullable<Decimal> IVD_REDUCEPER
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_IVD_REDUCEPER]);
            }
            set
            {
                if (value != null)
                    _dataRow[COLUMN_IVD_REDUCEPER] = value;

                else
                    _dataRow[COLUMN_IVD_REDUCEPER] = DBNull.Value;

            }
        }
        public Nullable<Decimal> IVD_REDUCEAMOUNT
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_IVD_REDUCEAMOUNT]);
            }
            set
            {
                if (value != null)
                    _dataRow[COLUMN_IVD_REDUCEAMOUNT] = value;

                else
                    _dataRow[COLUMN_IVD_REDUCEAMOUNT] = DBNull.Value;

            }
        }
        public Nullable<Decimal> IVD_REDUCEBASEAMOUNT
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_IVD_REDUCEBASEAMOUNT]);
            }
            set
            {
                if (value != null)
                    _dataRow[COLUMN_IVD_REDUCEBASEAMOUNT] = value;

                else
                    _dataRow[COLUMN_IVD_REDUCEBASEAMOUNT] = DBNull.Value;

            }
        }
        public Nullable<Decimal> IVD_VATTAXPER
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_IVD_VATTAXPER]);
            }
            set
            {
                if (value != null)
                    _dataRow[COLUMN_IVD_VATTAXPER] = value;

                else
                    _dataRow[COLUMN_IVD_VATTAXPER] = DBNull.Value;

            }
        }
        public Nullable<Decimal> IVD_VATTAXAMOUNT
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_IVD_VATTAXAMOUNT]);
            }
            set
            {
                if (value != null)
                    _dataRow[COLUMN_IVD_VATTAXAMOUNT] = value;

                else
                    _dataRow[COLUMN_IVD_VATTAXAMOUNT] = DBNull.Value;

            }
        }
        public Nullable<Decimal> IVD_VATTAXBASEAMOUNT
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_IVD_VATTAXBASEAMOUNT]);
            }
            set
            {
                if (value != null)
                    _dataRow[COLUMN_IVD_VATTAXBASEAMOUNT] = value;

                else
                    _dataRow[COLUMN_IVD_VATTAXBASEAMOUNT] = DBNull.Value;


            }
        }
        public Nullable<Decimal> IVD_EXCISETAXPER
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_IVD_EXCISETAXPER]);
            }
            set
            {
                if (value != null)
                    _dataRow[COLUMN_IVD_EXCISETAXPER] = value;

                else
                    _dataRow[COLUMN_IVD_EXCISETAXPER] = DBNull.Value;


            }
        }
        public Nullable<Decimal> IVD_EXCISETAXAMOUNT
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_IVD_EXCISETAXAMOUNT]);
            }
            set
            {
                if (value != null)
                    _dataRow[COLUMN_IVD_EXCISETAXAMOUNT] = value;

                else
                    _dataRow[COLUMN_IVD_EXCISETAXAMOUNT] = DBNull.Value;

            }
        }
        public Nullable<Decimal> IVD_EXCISETAXBASEAMOUNT
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_IVD_EXCISETAXBASEAMOUNT]);
            }
            set
            {
                if (value != null)
                    _dataRow[COLUMN_IVD_EXCISETAXBASEAMOUNT] = value;

                else
                    _dataRow[COLUMN_IVD_EXCISETAXBASEAMOUNT] = DBNull.Value;

            }
        }
        public Nullable<Decimal> IVD_IMEXPORTTAXPER
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_IVD_IMEXPORTTAXPER]);
            }
            set
            {
                if (value != null)
                    _dataRow[COLUMN_IVD_IMEXPORTTAXPER] = value;

                else
                    _dataRow[COLUMN_IVD_IMEXPORTTAXPER] = DBNull.Value;

            }
        }
        public Nullable<Decimal> IVD_IMEXPORTTAXAMOUNT
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_IVD_IMEXPORTTAXAMOUNT]);
            }
            set
            {
                if (value != null)
                    _dataRow[COLUMN_IVD_IMEXPORTTAXAMOUNT] = value;

                else
                    _dataRow[COLUMN_IVD_IMEXPORTTAXAMOUNT] = DBNull.Value;

            }
        }
        public Nullable<Decimal> IVD_IMEXPORTTAXBASEAMOUNT
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_IVD_IMEXPORTTAXBASEAMOUNT]);
            }
            set
            {
                if (value != null)
                    _dataRow[COLUMN_IVD_IMEXPORTTAXBASEAMOUNT] = value;

                else
                    _dataRow[COLUMN_IVD_IMEXPORTTAXBASEAMOUNT] = DBNull.Value;

            }
        }
        public Nullable<Decimal> IVD_TOTALAMOUNT
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_IVD_TOTALAMOUNT]);
            }
            set
            {
                if (value != null)
                    _dataRow[COLUMN_IVD_TOTALAMOUNT] = value;

                else
                    _dataRow[COLUMN_IVD_TOTALAMOUNT] = DBNull.Value;

            }
        }
        public Nullable<Decimal> IVD_TOTALBASEAMOUNT
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_IVD_TOTALBASEAMOUNT]);
            }
            set
            {
                if (value != null)
                    _dataRow[COLUMN_IVD_TOTALBASEAMOUNT] = value;

                else
                    _dataRow[COLUMN_IVD_TOTALBASEAMOUNT] = DBNull.Value;

            }
        }
        public String IVD_DESCRIPTION
        {
            get
            {
                return Convert.ToString(GetSafeObjectValue(_dataRow[COLUMN_IVD_DESCRIPTION], null));
            }
            set
            {
                _dataRow[COLUMN_IVD_DESCRIPTION] = value;
            }
        }
        public INVOICEDETAIL(IDataReader RederObject) : base(RederObject, TABLE_NAME) { }
        public INVOICEDETAIL(DataRow row) : base(row, TABLE_NAME) { }
        public INVOICEDETAIL()
            : base(TABLE_NAME, COLUMN_IVD_AUTOID,
            COLUMN_IV_DOCUMENTID,
            COLUMN_ITG_AUTOID,
            COLUMN_CP_AUTOID,
            COLUMN_PK_AUTOID,
            COLUMN_PIT_AUTOID,
            COLUMN_PIT_ITEMNAME,
            COLUMN_PIT_ITEMNO,
            COLUMN_COT_DOCUMENTID,
            COLUMN_TUR_AUTOID,
            COLUMN_WH_AUTOID,
            COLUMN_ITT_AUTOID,
            COLUMN_UOM_AUTOID,
            COLUMN_IVD_REQQUANTITY,
            COLUMN_IVD_QUANTITYREAL,
            COLUMN_IVD_UNITPRICE,
            COLUMN_IVD_UNITBASEPRICE,
            COLUMN_IVD_ITEMAMOUNT,
            COLUMN_IVD_ITEMBASEAMOUNT,
            COLUMN_IVD_REDUCEPER,
            COLUMN_IVD_REDUCEAMOUNT,
            COLUMN_IVD_REDUCEBASEAMOUNT,
            COLUMN_IVD_VATTAXPER,
            COLUMN_IVD_VATTAXAMOUNT,
            COLUMN_IVD_VATTAXBASEAMOUNT,
            COLUMN_IVD_EXCISETAXPER,
            COLUMN_IVD_EXCISETAXAMOUNT,
            COLUMN_IVD_EXCISETAXBASEAMOUNT,
            COLUMN_IVD_IMEXPORTTAXPER,
            COLUMN_IVD_IMEXPORTTAXAMOUNT,
            COLUMN_IVD_IMEXPORTTAXBASEAMOUNT,
            COLUMN_IVD_TOTALAMOUNT,
            COLUMN_IVD_TOTALBASEAMOUNT,
            COLUMN_IVD_DESCRIPTION) { }
    }
}

