///////////////////////////////////////////////////////////////////////////
// Description: Entity class for the 'PUBENTRY'
// Generated by VNYI GenTool.
// Copyright (c) YI Corp. All rights reserved.// Design by ngocchinh.//email:ngocchinh4984@gmail.com
///////////////////////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;

using System.Data;

namespace vnyi.Library.COMON.IV
{
    public class PUBENTRY : vnyi.DLL.DataObject
    {

        public static string COLUMN_DOC_DETAILID = "DOC_DETAILID";
        public static string COLUMN_COT_DOCUMENTID = "COT_DOCUMENTID";
        public static string COLUMN_DOC_PARRENTID = "DOC_PARRENTID";
        public static string COLUMN_ET_AUTOID = "ET_AUTOID";
        public static string COLUMN_ET_BUSSINESSID = "ET_BUSSINESSID";
        public static string COLUMN_ET_ISACTIVE = "ET_ISACTIVE";
        public static string COLUMN_ET_EXCHANGERATE = "ET_EXCHANGERATE";
        public static string COLUMN_ET_TOTALAMOUNT = "ET_TOTALAMOUNT";
        public static string COLUMN_ET_BASEAMOUNT = "ET_BASEAMOUNT";
        public static string COLUMN_OBJ_AUTOID = "OBJ_AUTOID";
        public static string COLUMN_CP_AUTOID = "CP_AUTOID";
        public static string COLUMN_COST_AUTOID = "COST_AUTOID";
        public static string COLUMN_ET_CREDITEXPLAIN = "ET_CREDITEXPLAIN";
        public static string COLUMN_ET_NOTE = "ET_NOTE";
        public static string COLUMN_ET_DEBTOREXPLAIN = "ET_DEBTOREXPLAIN";
        public static string COLUMN_ET_OFSUBSYSTEM = "ET_OFSUBSYSTEM";
        public static string COLUMN_ET_OFSYSTEM = "ET_OFSYSTEM";
        public static string COLUMN_PRJ_AUTOID = "PRJ_AUTOID";
        public static string COLUMN_BAK_AUTOID = "BAK_AUTOID";
        public static string COLUMN_CUR_AUTOID = "CUR_AUTOID";
        public static string COLUMN_PETT_AUTOID = "PETT_AUTOID";
        public static string COLUMN_ET_DEBTORACCOUNT = "ET_DEBTORACCOUNT";
        public static string COLUMN_ET_CREDITACCOUNT = "ET_CREDITACCOUNT";
        public static string COLUMN_CI_AUTOID = "CI_AUTOID";   
        public static string TABLE_NAME = "PUBENTRY";

        public Nullable<Int64> ET_AUTOID
        {
            get
            {
                return ConvertToInt64(_dataRow[COLUMN_ET_AUTOID]);
            }
            set
            {
                _dataRow[COLUMN_ET_AUTOID] = value;
            }
        }
        public Nullable<Int64> ET_BUSSINESSID
        {
            get
            {
                return ConvertToInt64(_dataRow[COLUMN_ET_BUSSINESSID]);
            }
            set
            {
                _dataRow[COLUMN_ET_BUSSINESSID] = value;
            }
        }
        public Nullable<Int64> DOC_PARRENTID
        {
            get
            {
                return ConvertToInt64(_dataRow[COLUMN_DOC_PARRENTID]);
            }
            set
            {
                _dataRow[COLUMN_DOC_PARRENTID] = value;
            }
        }
        public Nullable<Int64> DOC_DETAILID
        {
            get
            {
                return ConvertToInt64(_dataRow[COLUMN_DOC_DETAILID]);
            }
            set
            {
                _dataRow[COLUMN_DOC_DETAILID] = value;
            }
        }
        public Nullable<Int16> PRJ_AUTOID
        {
            get
            {
                return ConvertToInt16(_dataRow[COLUMN_PRJ_AUTOID]);
            }
            set
            {
                _dataRow[COLUMN_PRJ_AUTOID] = value;
            }
        }
        public Nullable<int> CP_AUTOID
        {
            get
            {
                return ConvertToInt32(_dataRow[COLUMN_CP_AUTOID]);
            }
            set
            {
                _dataRow[COLUMN_CP_AUTOID] = value;
            }
        }
        public Nullable<int> OBJ_AUTOID
        {
            get
            {
                return ConvertToInt32(_dataRow[COLUMN_OBJ_AUTOID]);
            }
            set
            {
                _dataRow[COLUMN_OBJ_AUTOID] = value;
            }
        }
        public Nullable<Int16> BAK_AUTOID
        {
            get
            {
                return ConvertToInt16(_dataRow[COLUMN_BAK_AUTOID]);
            }
            set
            {
                _dataRow[COLUMN_BAK_AUTOID] = value;
            }
        }
        public Nullable<Int64> COT_DOCUMENTID
        {
            get
            {
                return ConvertToInt64(_dataRow[COLUMN_COT_DOCUMENTID]);
            }
            set
            {
                _dataRow[COLUMN_COT_DOCUMENTID] = value;
            }
        }
        public Nullable<int> COST_AUTOID
        {
            get
            {
                return ConvertToInt32(_dataRow[COLUMN_COST_AUTOID]);
            }
            set
            {
                _dataRow[COLUMN_COST_AUTOID] = value;
            }
        }
        public Nullable<Int16> CUR_AUTOID
        {
            get
            {
                return ConvertToInt16(_dataRow[COLUMN_CUR_AUTOID]);
            }
            set
            {
                _dataRow[COLUMN_CUR_AUTOID] = value;
            }
        }
        public String ET_DEBTORACCOUNT
        {
            get
            {
                return Convert.ToString(GetSafeObjectValue(_dataRow[COLUMN_ET_DEBTORACCOUNT], null));
            }
            set
            {
                _dataRow[COLUMN_ET_DEBTORACCOUNT] = value;
            }
        }
        public String ET_DEBTOREXPLAIN
        {
            get
            {
                return Convert.ToString(GetSafeObjectValue(_dataRow[COLUMN_ET_DEBTOREXPLAIN], null));
            }
            set
            {
                _dataRow[COLUMN_ET_DEBTOREXPLAIN] = value;
            }
        }
        public String ET_CREDITACCOUNT
        {
            get
            {
                return Convert.ToString(GetSafeObjectValue(_dataRow[COLUMN_ET_CREDITACCOUNT], null));
            }
            set
            {
                _dataRow[COLUMN_ET_CREDITACCOUNT] = value;
            }
        }
        public String ET_CREDITEXPLAIN
        {
            get
            {
                return Convert.ToString(GetSafeObjectValue(_dataRow[COLUMN_ET_CREDITEXPLAIN], null));
            }
            set
            {
                _dataRow[COLUMN_ET_CREDITEXPLAIN] = value;
            }
        }
        public Nullable<Decimal> ET_EXCHANGERATE
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_ET_EXCHANGERATE]);
            }
            set
            {
                _dataRow[COLUMN_ET_EXCHANGERATE] = value;
            }
        }
        public Nullable<Decimal> ET_TOTALAMOUNT
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_ET_TOTALAMOUNT]);
            }
            set
            {
                _dataRow[COLUMN_ET_TOTALAMOUNT] = value;
            }
        }
        public Nullable<Decimal> ET_BASEAMOUNT
        {
            get
            {
                return ConvertDecimalnull(_dataRow[COLUMN_ET_BASEAMOUNT]);
            }
            set
            {
                _dataRow[COLUMN_ET_BASEAMOUNT] = value;
            }
        }
        public String ET_NOTE
        {
            get
            {
                return Convert.ToString(GetSafeObjectValue(_dataRow[COLUMN_ET_NOTE], null));
            }
            set
            {
                _dataRow[COLUMN_ET_NOTE] = value;
            }
        }
        public Nullable<Int16> ET_OFSYSTEM
        {
            get
            {
                return ConvertToInt16(_dataRow[COLUMN_ET_OFSYSTEM]);
            }
            set
            {
                _dataRow[COLUMN_ET_OFSYSTEM] = value;
            }
        }
        public Nullable<Int16> ET_OFSUBSYSTEM
        {
            get
            {
                return ConvertToInt16(_dataRow[COLUMN_ET_OFSUBSYSTEM]);
            }
            set
            {
                _dataRow[COLUMN_ET_OFSUBSYSTEM] = value;
            }
        }
        public bool ET_ISACTIVE
        {
            get
            {
                return ConvertToBoolean(_dataRow[COLUMN_ET_ISACTIVE]);
            }
            set
            {
                _dataRow[COLUMN_ET_ISACTIVE] = value;
            }
        }
        public Nullable<Int16> PETT_AUTOID
        {
            get
            {
                return ConvertToInt16(_dataRow[COLUMN_PETT_AUTOID]);
            }
            set
            {
                _dataRow[COLUMN_PETT_AUTOID] = value;
            }
        }
        public Nullable<int> CI_AUTOID
        {
            get
            {
                return ConvertToInt32(_dataRow[COLUMN_CI_AUTOID]);
            }
            set
            {
                _dataRow[COLUMN_CI_AUTOID] = value;
            }
        }
        public PUBENTRY(IDataReader RederObject) : base(RederObject, TABLE_NAME) { }
        public PUBENTRY(DataRow row) : base(row, TABLE_NAME) { }
        public PUBENTRY()
            : base(TABLE_NAME, COLUMN_ET_AUTOID,
            COLUMN_ET_BUSSINESSID,
            COLUMN_DOC_PARRENTID,
            COLUMN_DOC_DETAILID,
            COLUMN_PRJ_AUTOID,
            COLUMN_CP_AUTOID,
            COLUMN_OBJ_AUTOID,
            COLUMN_BAK_AUTOID,
            COLUMN_COT_DOCUMENTID,
            COLUMN_COST_AUTOID,
            COLUMN_CUR_AUTOID,
            COLUMN_ET_DEBTORACCOUNT,
            COLUMN_ET_DEBTOREXPLAIN,
            COLUMN_ET_CREDITACCOUNT,
            COLUMN_ET_CREDITEXPLAIN,
            COLUMN_ET_EXCHANGERATE,
            COLUMN_ET_TOTALAMOUNT,
            COLUMN_ET_BASEAMOUNT,
            COLUMN_ET_NOTE,
            COLUMN_ET_OFSYSTEM,
            COLUMN_ET_OFSUBSYSTEM,
            COLUMN_ET_ISACTIVE,
            COLUMN_PETT_AUTOID,
            COLUMN_CI_AUTOID) { }
    }
}

