///////////////////////////////////////////////////////////////////////////
// Description: Entity class for the 'PUBPLAN'
// Generated by VNYI GenTool.
// Copyright (c) YI Corp. All rights reserved.
///////////////////////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.Data;


namespace vnyi.Library.PLA
{
    public class PUBPLAN : vnyi.DLL.DataObject
    {

        public static string COLUMN_PLA_DOCUMENTID = "PLA_DOCUMENTID";
        public static string COLUMN_PLA_ENDDATE = "PLA_ENDDATE";
        public static string COLUMN_PLA_BEGINDATE = "PLA_BEGINDATE";
        public static string COLUMN_PLA_AMOUNT = "PLA_AMOUNT";
        public static string COLUMN_PLA_AMOUNTREAL = "PLA_AMOUNTREAL";
        public static string COLUMN_OBJ_AUTOID = "OBJ_AUTOID";
        public static string COLUMN_PLA_RESION = "PLA_RESION";
        public static string COLUMN_DOTY_AUTOID = "DOTY_AUTOID";
        public static string COLUMN_ST_AUTOID = "ST_AUTOID";
        public static string COLUMN_PLA_BASEAMOUNT = "PLA_BASEAMOUNT";
        public static string COLUMN_CUR_AUTOID = "CUR_AUTOID";
        public static string COLUMN_PLA_EXCHANGERATE = "PLA_EXCHANGERATE";

        public static string TABLE_NAME = "PUBPLAN";

        public Nullable<Int64> PLA_DOCUMENTID
        {
            get
            {
                return ConvertToInt64(GetSafeObjectValue(_dataRow[COLUMN_PLA_DOCUMENTID], -1));
            }
            set
            {
                _dataRow[COLUMN_PLA_DOCUMENTID] = GetSafeObjectValue(value, -1);
            }
        }

        public Nullable<Int16> DOTY_AUTOID
        {
            get
            {
                return ConvertToInt16(GetSafeObjectValue(_dataRow[COLUMN_DOTY_AUTOID], -1));
            }
            set
            {
                _dataRow[COLUMN_DOTY_AUTOID] = GetSafeObjectValue(value, -1);
            }
        }
        public Nullable<Int16> ST_AUTOID
        {
            get
            {
                return ConvertToInt16(GetSafeObjectValue(_dataRow[COLUMN_ST_AUTOID], -1));
            }
            set
            {
                _dataRow[COLUMN_ST_AUTOID] = GetSafeObjectValue(value, -1);
            }
        }
        public decimal PLA_AMOUNTREAL
        {
            get
            {
                return Convert.ToDecimal(GetSafeObjectValue(_dataRow[COLUMN_PLA_AMOUNTREAL], -1));
            }
            set
            {
                _dataRow[COLUMN_PLA_AMOUNTREAL] = Convert.ToDecimal(GetSafeObjectValue(value, -1));
            }
        }

        public DateTime PLA_BEGINDATE
        {
            get
            {
                return Convert.ToDateTime(GetSafeObjectValue(_dataRow[COLUMN_PLA_BEGINDATE], DateTime.MinValue));
            }
            set
            {
                _dataRow[COLUMN_PLA_BEGINDATE] = Convert.ToDateTime(GetSafeObjectValue(value, DateTime.MinValue));
            }
        }
        public DateTime PLA_ENDDATE
        {
            get
            {
                return Convert.ToDateTime(GetSafeObjectValue(_dataRow[COLUMN_PLA_ENDDATE], DateTime.MinValue));
            }
            set
            {
                _dataRow[COLUMN_PLA_ENDDATE] = Convert.ToDateTime(GetSafeObjectValue(value, DateTime.MinValue));
            }
        }
        public decimal PLA_AMOUNT
        {
            get
            {
                return Convert.ToDecimal(GetSafeObjectValue(_dataRow[COLUMN_PLA_AMOUNT], -1));
            }
            set
            {
                _dataRow[COLUMN_PLA_AMOUNT] = Convert.ToDecimal(GetSafeObjectValue(value, -1));
            }
        }
        public Nullable<int> OBJ_AUTOID
        {
            get
            {
                return ConvertToInt32(GetSafeObjectValue(_dataRow[COLUMN_OBJ_AUTOID], null));
            }
            set
            {
                _dataRow[COLUMN_OBJ_AUTOID] = ConvertToInt32(GetSafeObjectValue(value, null));
            }
        }
        public string PLA_RESION
        {
            get
            {
                return Convert.ToString(GetSafeObjectValue(_dataRow[COLUMN_PLA_RESION], null));
            }
            set
            {
                _dataRow[COLUMN_PLA_RESION] = Convert.ToString(GetSafeObjectValue(value, null));
            }
        }
        public decimal PLA_BASEAMOUNT
        {
            get
            {
                return Convert.ToDecimal(GetSafeObjectValue(_dataRow[COLUMN_PLA_BASEAMOUNT], -1));
            }
            set
            {
                _dataRow[COLUMN_PLA_BASEAMOUNT] = Convert.ToDecimal(GetSafeObjectValue(value, -1));
            }
        }
        public Nullable<Int16> CUR_AUTOID
        {
            get
            {
                return ConvertToInt16(GetSafeObjectValue(_dataRow[COLUMN_CUR_AUTOID], -1));
            }
            set
            {
                _dataRow[COLUMN_CUR_AUTOID] = GetSafeObjectValue(value, -1);
            }
        }
        public decimal PLA_EXCHANGERATE
        {
            get
            {
                return Convert.ToDecimal(GetSafeObjectValue(_dataRow[COLUMN_PLA_EXCHANGERATE], -1));
            }
            set
            {
                _dataRow[COLUMN_PLA_EXCHANGERATE] = Convert.ToDecimal(GetSafeObjectValue(value, -1));
            }
        }

        public PUBPLAN(DataRow row) : base(row, TABLE_NAME) { }
        public PUBPLAN(IDataReader iReader) : base(iReader, TABLE_NAME) { }
        public PUBPLAN()
            : base(TABLE_NAME
                   , COLUMN_PLA_DOCUMENTID
                    , COLUMN_PLA_ENDDATE
                    , COLUMN_PLA_BEGINDATE
                    , COLUMN_PLA_AMOUNT
                    , COLUMN_PLA_AMOUNTREAL
                    , COLUMN_OBJ_AUTOID
                    , COLUMN_PLA_RESION
                    , COLUMN_DOTY_AUTOID
                    , COLUMN_ST_AUTOID
                    , COLUMN_PLA_BASEAMOUNT
                    , COLUMN_CUR_AUTOID
                    , COLUMN_PLA_EXCHANGERATE
                ) { }
    }
}

